Fix execCommand link
w3c/editing pull request #245
Opened 2020-05-03 18:39 UTC by saschanaz

Since it's in ActiveDocuments directory.

2020-05-04 05:32 UTC, marcoscaceres commented
Well, this it's complicated... it's a maintained document, but there is zero expectation of ever standardizing, right?

2020-05-04 07:15 UTC, saschanaz commented
@marcoscaceres It's already in that directory, only the link is broken.

2020-05-06 23:56 UTC, johanneswilm commented
Hey @gked - I suspect you accidentally moved the execCommand document into the `ActiveDocuments` folder. I assume you meant to put it into the `Archive` folder, right?

2020-05-12 03:36 UTC, marcoscaceres requested changes
I should probably go back into archived. We can still maintain it when there is glaring inconsistencies/errors, but let's not give false hope that it's going anywhere.

2020-05-12 03:38 UTC, marcoscaceres commented
What might be useful is to figure out what we might be able to salvage and maybe push that into HTML? This may just be tiny little things, but every little thing we salvage is a win. There would have to be clear evidence of interoperability.

2020-05-12 06:50 UTC, johanneswilm commented
We decided on the call on Friday to do as you say and put it back into Archived. It does not prevent us from editing the file when need be.

2020-05-12 06:53 UTC, marcoscaceres commented
Sounds great @johanneswilm. Thanks for the update!

2020-05-12 09:21 UTC, saschanaz commented
> but let's not give false hope that it's going anywhere.

"Archived" also gives false information that those will never be maintained. It should really be "Inactive" or something.

2020-07-13 12:20 UTC, saschanaz commented
This is fixed by #264.

2020-07-13 12:20 UTC, closed without merging