Update spec draft, explainer, examples for EditContext
w3c/editing pull request #355
Opened 2021-10-25 20:43 UTC by alexkeng

This PR adds Editor's draft for EditContext spec (index.html), revises the Explainer (explainer.md), and adds new example (canvas_editContext.html).

2021-10-25 21:21 UTC, travisleithead commented
Easy readable version for review here: https://alexkeng.github.io/editing/docs/EditContext/index.html

2021-10-25 22:14 UTC, travisleithead requested changes
Just a few minor changes. Looks excellent. Great update!

2021-10-25 22:14 UTC, travisleithead commented on docs/EditContext/index.html
> +                let lineStartX = anchorX + textFormat.rangeStart * charWidth;
A few of these variables are used, but not defined. Might be good to note what they are in comments? (I understand that this is example code and that these variables are largely self-explanatory...)

2021-10-25 22:14 UTC, travisleithead commented on docs/EditContext/index.html
> +                let lineStartX = anchorX + textFormat.rangeStart * charWidth;
e.g., `anchorX`, `charWidth`, `thickWidth`, `lineY`...

2021-10-25 22:14 UTC, travisleithead commented on docs/EditContext/index.html
> +        editingcontroller.updateTextFormatsUpdate(e.getTextFormats());
```suggestion
        editingcontroller.handleTextFormatUpdate(e.getTextFormats());
```

2021-10-25 22:14 UTC, travisleithead commented on docs/EditContext/index.html
> +            let range = document.createRange()
```suggestion
            let range = new Range()
```

2021-10-25 22:14 UTC, travisleithead commented on docs/EditContext/index.html
> +            let range = document.createRange()
(Just a more modern approach...)

2021-10-25 22:40 UTC, alexkeng commented on docs/EditContext/index.html
> +            let range = document.createRange()
sure, updated to new Range()

2021-10-25 22:40 UTC, alexkeng commented on docs/EditContext/index.html
> +        editingcontroller.updateTextFormatsUpdate(e.getTextFormats());
good catch!

2021-10-25 22:40 UTC, alexkeng commented on docs/EditContext/index.html
> +                let lineStartX = anchorX + textFormat.rangeStart * charWidth;
sure! comment added

2021-10-25 22:42 UTC, alexkeng commented on docs/EditContext/index.html
> +            let range = document.createRange()
thanks for the quick review!

2021-10-26 07:15 UTC, xfq commented
FWIW, the link to the demo video in [Example Application](https://github.com/w3c/editing/blob/23711b55bb7a8b388d8691372b79441152107ebe/docs/EditContext/explainer.md#example-application) emitted:

> Sorry, the link has expired.
> The link was set to expire after a certain amount of time. Please contact the person who shared this link with you.

I don't know if there's an issue with the URL or it's just me.

2021-10-26 16:42 UTC, travisleithead approved these changes
Awesome. Lets get this merged.

2021-10-26 16:45 UTC, merged